# ============================================================
# DOCKERFILE — FRONTEND INDUSTRIAL (PROYECTO-GRUPO-4)
# HTML + CSS + JS + NGINX
# ============================================================

FROM nginx:alpine

# Remover configuración por defecto
RUN rm /etc/nginx/conf.d/default.conf

# Copiar configuración personalizada de NGINX
COPY nginx.conf /etc/nginx/conf.d/

# Copiar todos los archivos del frontend
COPY src/frontend /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
