server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # MUY IMPORTANTE — permitir ES Modules
    types {
        application/javascript js mjs;
        text/css css;
        text/html html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
